### ISSUE TITLE
Install through npm not working

### ISSUE THREAD

**Issue by khepin** [tactivos/grunt-htmlrefs#3]
Running: `sudo npm install grunt-htmlrefs --save-dev` (with or without `--save-dev` has the same outcome), I get the error that version 0.2.3 does not exist:

```
npm http GET https://registry.npmjs.org/grunt-htmlrefs
npm http 304 https://registry.npmjs.org/grunt-htmlrefs
npm http GET https://registry.npmjs.org/grunt-htmlrefs/-/grunt-htmlrefs-0.2.3.tgz
npm http 404 https://registry.npmjs.org/grunt-htmlrefs/-/grunt-htmlrefs-0.2.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/grunt-htmlrefs/-/grunt-htmlrefs-0.2.3.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at null.<anonymous> (/usr/share/npm/lib/utils/fetch.js:47:16)
npm ERR!     at EventEmitter.emit (events.js:126:20)
npm ERR!     at WriteStream.flush (fs.js:1529:12)
npm ERR!     at fs.close (/usr/share/npm/node_modules/graceful-fs/graceful-fs.js:90:5)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.5.0-17-generic
npm ERR! command "nodejs" "/usr/bin/npm" "install" "grunt-htmlrefs"
npm ERR! cwd /home/seb/projects/smp
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/seb/projects/smp/npm-debug.log
npm ERR! not ok code 0
```

**Comment by johnnyhalife** [comment]
It should be working now sorry.

On Fri, Jan 11, 2013 at 12:30 AM, Sebastien Armand <notifications@github.com
